// packages/react/src/useFieldValue.js
import {
	useCallback,
	useContext,
	useEffect,
	useState,
} from 'react'

import ValuesContext from './ValuesContext.js'

const useFieldValue = ({
	name,
}) => {
	const {
		getFieldValue,
		setFieldValue,
		subscribeToFieldValue,
	} = (
		useContext(
			ValuesContext
		)
	)

	const [
		localValue,
		setLocalValue,
	] = (
		useState(
			getFieldValue(
				name
			)
		)
	)

	const setValue = (
		useCallback(
			(
				value,
			) => {
				setFieldValue(
					name,
					value,
				)
			},
			[
				name,
				setFieldValue,
			],
		)
	)

	useEffect(
		() => (
			subscribeToFieldValue({
				identifier: (
					name
				),
				subscriber: (
					setLocalValue
				),
			})
		),
		[
			name,
			subscribeToFieldValue,
		],
	)

	return {
		setValue,
		value: localValue,
	}
}

export default useFieldValue

// packages/solid/src/useFieldValue.js
import {
  useContext,
} from 'solid-js'

import ValuesContext from './ValuesContext.js'

const useFieldValue = ({
  name,
}) => {
  const {
    getFieldValue,
  } = (
    useContext(
      ValuesContext
    )
  )

  const {
    getValue,
    setValue,
  } = (
    getFieldValue(
      name
    )
  )

  return {
    getValue,
    setValue,
  }
}

export default useFieldValue
